name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: debug commit message
        run: echo "ok"

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: Install dependencies 
  #       run: npm install  
  #
  #     - name: Check style
  #       run: npm run eslint
  #
  #     - name: Build
  #       run: npm run build
  #
  #     - if: ${{ failure() }}
  #       run:
  #         echo "ei toimi, mut toimii"
  #
  #     - name: Test
  #       run: npm run test
  #
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
  #     - uses: actions/checkout@v4
        - name: Bump version and push tag
          run: echo " ${{ github.event.commits.*.url }} by ${{ github.event.commits.*.author.username}}"
  #       uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch
  #
  #
  # production_deployment:
  #     needs: [tag_release]
  #     runs-on: ubuntu-20.04
  #     steps:
  #       - uses: actions/checkout@v4
  #       - uses: superfly/flyctl-actions/setup-flyctl@master
  #       - name: deploy to production
  #         run: flyctl deploy --remote-only
  #         env:
  #           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  #
  #       - name: Success
  #         uses: rjstone/discord-webhook-notify@v1.0.4
  #         if: success()
  #         with:
  #           severity: info
  #           description: to https://full-stack-open-pokedex-shoutcape.fly.dev/ by shoutcape
  #           avatarUrl: https://avatars.githubusercontent.com/u/74509593?s=400&u=5669e74c289240db364d1f89c95a9ffc1a5db0e5&v=4
  #           text: A new version of Pokedex deployed 
  #           footer: "Severity: informational"
  #           webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  #
  #
  #       - name: Failure
  #         uses: rjstone/discord-webhook-notify@v1.0.4
  #         if: failure()
  #         with:
  #           severity: error
  #           description: commit
  #           avatarUrl: https://avatars.githubusercontent.com/u/74509593?s=400&u=5669e74c289240db364d1f89c95a9ffc1a5db0e5&v=4
  #           details: ${{ github.event.commits.*.url }}
  #           text: Build failed 
  #           footer: This is a footer.
  #           webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


# - name: Test Custom
#     with:
#         severity: info
#         details: 'Custom details: Somebody set up us the bomb.'
#         footer: This is a footer.
