name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      # - name: debug commit message
        # run: echo "**${{ github.event.pull_request.title }}**\n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}" 

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch


  production_deployment:
      needs: [tag_release]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: deploy to production
          run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

        - name: Success
          if: success()
          uses: stegzilla/discord-notify@v4
          with:
            title: A new version of Pokedex deployed
            avatar_url: https://avatars.githubusercontent.com/u/74509593?s=400&u=5669e74c289240db364d1f89c95a9ffc1a5db0e5&v=4
            colour: '#008000'
            message: to https://full-stack-open-pokedex-shoutcape.fly.dev/ by shoutcape
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}


        - name: Failure
          if: failure() && ${{ github.event_name == 'push'}}
          uses: stegzilla/discord-notify@v4
          with:
            title: Build failed
            avatar_url: https://avatars.githubusercontent.com/u/74509593?s=400&u=5669e74c289240db364d1f89c95a9ffc1a5db0e5&v=4
            colour: '#FF0000'
            message: "${{ toJson(github.event.head_commit.url) }} by ${{ toJson(github.event.head_commit.author.username) }}"
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
