name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]
# some text
env:
  SKIP: ${{ join(github.event.commits.*.message,' ') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: debug commit message
        run: echo "${{ toJson(github.event.commits) }}"

      - if : ${{ contains(env.SKIP, '#skip') }}
        run: echo "toimii"

    #   - uses: actions/setup-node@v4
    #     with:
    #       node-version: '20'
    #   - name: Install dependencies 
    #     run: npm install  
    #
    #   - name: Check style
    #     run: npm run eslint
    #
    #   - name: Build
    #     run: npm run build
    #
    #   - name: Test
    #     run: npm run test

  # tag_release:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-20.04
  #   if: ${{ github.event.pull_request.merged && !contains(github.event..message, '#skip') }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Bump version and push tag
  #       uses: anothrNick/github-tag-action@1.70.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch


  # production_deployment:
  #     needs: [tag_release]
  #     runs-on: ubuntu-20.04
  #     steps:
  #       - uses: actions/checkout@v4
  #       - uses: superfly/flyctl-actions/setup-flyctl@master
  #       - name: deploy to production
  #         run: flyctl deploy --remote-only
  #         env:
  #           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
