name: health-check

on:
  schedule:
    - cron: '2 * * * *'

jobs:
  scheduled-health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: every day
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-shoutcape.fly.dev/
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1


      - name: failure
        if: failure()
        run: 
          echo "health-check failed"

          
      - name: success
        if: success()
        run: 
          echo "health-check success"
        


  
